name: Trigger nightly build
on: 
  issue_comment:
    types: [created]

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Nightly build
          branch: main
          commit_options: "--allow-empty"
